import { Game } from "./types";

export const GBA_GAMES: Game[] = [
  /*
      // --- GAME BOY ADVANCE (GBA) GAMES ---
  {
    id: 'pokemon_ruby_sapphire',
    title: 'Pokémon - Ruby Version & Sapphire Version',
    publisher: 'Nintendo / Game Freak',
    year: 2002,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Pokemon%20-%20Ruby%20Version%20%26%20Sapphire%20Version.zip/Pokemon%20-%20Saphir-Edition%20%28G%29%20%28V1.0%29.gba',
    description: 'Explore the vast, water-filled Hoenn region, meet the third generation of Pokémon, and fight back Team Magma or Team Aqua.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-water',
    system: 'gba'
  },
  {
    id: 'pokemon_emerald',
    title: 'Pokémon - Emerald Version',
    publisher: 'Nintendo / Game Freak',
    year: 2004,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Pokemon%20-%20Emerald%20Version.zip/Pokemon%20-%20Emerald%20%28J%29.gba',
    description: 'The definitive Hoenn adventure. Command premium battle strategies inside Battle Frontier to stop Groudon and Kyogre clash using Rayquaza.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-gem',
    system: 'gba'
  },
  {
    id: 'pokemon_leafgreen_firered',
    title: 'Pokémon - Leaf Green Version & Fire Red Version',
    publisher: 'Nintendo / Game Freak',
    year: 2004,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Pokemon%20-%20Leaf%20Green%20Version%20%26%20Fire%20Red%20Version.zip/Pokemon%20-%20Fire%20Red%20%28J%29%20%28V1.0%29.gba',
    description: 'Re-explore Kanto in a gorgeous expanded layout. Journey to complete the Pokédex and conquer elite league championships.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-fire',
    system: 'gba'
  },
  {
    id: 'pokemon_mystery_dungeon',
    title: 'Pokémon Mystery Dungeon - Red Rescue Team',
    publisher: 'Nintendo / Chunsoft',
    year: 2005,
    genre: 'Dungeon Crawler',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Pokemon%20Mystery%20Dungeon%20-%20Red%20Rescue%20Team.zip/Pokemon%20Mystery%20Dungeon%20-%20Red%20Rescue%20Team%20%28E%29%20%28M5%29.gba',
    description: 'Wake up directly as a Pokémon! Cooperate with companions inside mystery dungeons to execute heroic rescues and discover your identity.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-compass',
    system: 'gba'
  },
  {
    id: 'pokemon_pinball_rs',
    title: 'Pokémon Pinball - Ruby & Sapphire',
    publisher: 'Nintendo / Jupiter',
    year: 2003,
    genre: 'Pinball',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Pokemon%20Pinball%20-%20Ruby%20%26%20Sapphire.zip/Pokemon%20Pinball%20-%20Ruby%20%26%20Sapphire%20%28E%29%20%28M5%29.gba',
    description: 'Launch Pokéball pinballs across vibrant boards, catch and hatch Pokémon, and record high score combinations.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-circle-dot',
    system: 'gba'
  },
  {
    id: 'zelda_alttp_fourswords',
    title: 'The Legend of Zelda: A Link To The Past / Four Swords',
    publisher: 'Nintendo / Capcom',
    year: 2002,
    genre: 'Action-Adventure',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20To%20The%20Past%20Four%20Swords.zip/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20To%20The%20Past%20Four%20Swords%20%28E%29%20%28M5%29%20%5B%21%5D.gba',
    description: 'Experience the SNES classic Link to the Past enhanced on GBA, paired with the cooperative multi-player Four Swords.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-shield-halved',
    system: 'gba'
  },
  {
    id: 'zelda_minish_cap',
    title: 'The Legend of Zelda: The Minish Cap',
    publisher: 'Nintendo / Capcom',
    year: 2004,
    genre: 'Action-Adventure',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap.zip/Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20%28E%29%20%28M5%29.gba',
    description: 'Shrink Link down to microscopic proportions with Ezlo the magic hat to explore the hidden Minish world.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-hat-wizard',
    system: 'gba'
  },
  {
    id: 'metroid_fusion',
    title: 'Metroid Fusion',
    publisher: 'Nintendo',
    year: 2002,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Metroid%20Fusion.zip/Metroid%20Fusion%20%28U%29%20%5B%21%5D.gba',
    description: 'Survive on a space biological research station haunted by the deadly X parasite mimicking Samus\'s peak capabilities.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-radiation',
    system: 'gba'
  },
  {
    id: 'metroid_zero_mission',
    title: 'Metroid - Zero Mission',
    publisher: 'Nintendo',
    year: 2004,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Metroid%20-%20Zero%20Mission.zip/Metroid%20-%20Zero%20Mission%20%28U%29%20%5B%21%5D.gba',
    description: 'Re-live bounty hunter Samus Aran\'s original mission on Planet Zebes in of the finest action platform revisions ever made.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-jet-fighter',
    system: 'gba'
  },
  {
    id: 'castlevania_aria',
    title: 'Castlevania - Aria of Sorrow',
    publisher: 'Konami',
    year: 2003,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Castlevania%20-%20Aria%20of%20Sorrow.zip/Castlevania%20-%20Aria%20of%20Sorrow%20%28U%29%20%5B%21%5D.gba',
    description: 'Play as Soma Cruz inside Dracula\'s eclipse-entombed castle. Command monsters\' souls to unleash magic.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-ghost',
    system: 'gba'
  },
  {
    id: 'castlevania_circle',
    title: 'Castlevania - Circle of the Moon',
    publisher: 'Konami',
    year: 2001,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Castlevania%20-%20Circle%20of%20the%20Moon.zip/Castlevania%20-%20Circle%20of%20the%20Moon%20%28U%29%20%5B%21%5D.gba',
    description: 'Confront Carmilla and Dracula inside dark chambers using customizable card combinations.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-skull',
    system: 'gba'
  },
  {
    id: 'castlevania_harmony',
    title: 'Castlevania - Harmony of Dissonance',
    publisher: 'Konami',
    year: 2002,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Castlevania%20-%20Harmony%20of%20Dissonance.zip/Castlevania%20-%20Harmony%20of%20Dissonance%20%28E%29%20%5B%21%5D.gba',
    description: 'Direct Juste Belmont through parallel castle dimensions to retrieve a lost childhood companion.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-wand-magic',
    system: 'gba'
  },
  {
    id: 'castlevania_double_pack',
    title: '2-in-1 - Castlevania Double Pack - Harmony of Dissonance & Aria of Sorrow',
    publisher: 'Konami',
    year: 2005,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/2-in-1%20-%20Castlevania%20Double%20Pack%20-%20Harmony%20of%20Dissonance%20%26%20Aria%20of%20Sorrow.zip/2-in-1%20-%20Castlevania%20Double%20Pack%20-%20Harmony%20of%20Dissonance%20%26%20Aria%20of%20Sorrow%20%28U%29.gba',
    description: 'Get two of the best GBA Metroidvania games of all time in a single, gorgeous emulator cartridge package.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-skull-crossbones',
    system: 'gba'
  },
  {
    id: 'golden_sun',
    title: 'Golden Sun',
    publisher: 'Nintendo / Camelot',
    year: 2001,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Golden%20Sun.zip/Golden%20Sun%20%28UE%29%20%5B%21%5D.gba',
    description: 'Unleash direct elemental psynergy magic onto enemies and direct fantasy party alignments in this visually stunning RPG.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-sun',
    system: 'gba'
  },
  {
    id: 'golden_sun_lost_age',
    title: 'Golden Sun - The Lost Age',
    publisher: 'Nintendo / Camelot',
    year: 2002,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Golden%20Sun%20-%20The%20Lost%20Age.zip/Golden%20Sun%20-%20The%20Lost%20Age%20%28UE%29%20%5B%21%5D.gba',
    description: 'Confront alchemy dilemmas from the opposing side\'s perspective in the breathtaking, direct epic sequel to Golden Sun.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-hourglass-start',
    system: 'gba'
  },
  {
    id: 'mario_luigi_superstar',
    title: 'Mario & Luigi - Superstar Saga',
    publisher: 'Nintendo / AlphaDream',
    year: 2003,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20%26%20Luigi%20-%20Superstar%20Saga.zip/Mario%20%26%20Luigi%20-%20Superstar%20Saga%20%28U%29.gba',
    description: 'Command both Mario and Luigi simultaneously using action commands inside the bizarre, hilarity-filled Beanbean Kingdom.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-users',
    system: 'gba'
  },
  {
    id: 'super_mario_advance_1',
    title: 'Super Mario Advance (Super Mario Bros. 2)',
    publisher: 'Nintendo',
    year: 2001,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Super%20Mario%20Advance.zip/Super%20Mario%20Advance%20%28U%29%20%5B%21%5D.gba',
    description: 'Throw radishes, ride carpets, and battle Wart in this gorgeous classic GBA launch titles platformer adaptation.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-circle-plus',
    system: 'gba'
  },
  {
    id: 'super_mario_advance_2',
    title: 'Super Mario Advance 2 - Super Mario World',
    publisher: 'Nintendo',
    year: 2001,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Super%20Mario%20Advance%202%20-%20Super%20Mario%20World.zip/Super%20Mario%20Advance%202%20-%20Super%20Mario%20World%20%28U%29%20%5B%21%5D.gba',
    description: 'Super Mario World, meticulously adapted to hand-held controls. Collect stars, ride Yoshi, and defeat Bowser.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-egg',
    system: 'gba'
  },
  {
    id: 'super_mario_advance_3',
    title: "Super Mario Advance 3 - Yoshi's Island",
    publisher: 'Nintendo',
    year: 2002,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Super%20Mario%20Advance%203%20-%20Yoshi%27s%20Island.zip/Super%20Mario%20Advance%203%20-%20Yoshi%27s%20Island%20%28U%29%20%5B%21%5D.gba',
    description: 'Yoshi\'s Island platforming perfection on the go. Protect Baby Mario, throw eggs, and destroy Kamek\'s spells.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-clover',
    system: 'gba'
  },
  {
    id: 'super_mario_advance_4',
    title: 'Super Mario Advance 4 - Super Mario Bros. 3',
    publisher: 'Nintendo',
    year: 2003,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Super%20Mario%20Advance%204%20-%20Super%20Mario%20Bros.%203.zip/Super%20Mario%20Advance%204%20-%20Super%20Mario%20Bros.%203%20%28U%29%20%28V1.0%29.gba',
    description: 'The golden NES classic Super Mario Bros 3 enhanced on GBA, complete with dynamic colors and vocal prompts.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-feather',
    system: 'gba'
  },
  {
    id: 'mario_kart_super_circuit',
    title: 'Mario Kart Super Circuit',
    publisher: 'Nintendo / Intelligent Systems',
    year: 2001,
    genre: 'Kart Racing',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20Kart%20Super%20Circuit.zip/Mario%20Kart%20Super%20Circuit%20%28U%29%20%5B%21%5D.gba',
    description: 'Enjoy 40 unique hand-held kart racing tracks, drift curves, and launch shells across GBA and retro circuits.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-flag-checkered',
    system: 'gba'
  },
  {
    id: 'mario_golf_advance_tour',
    title: 'Mario Golf - Advance Tour',
    publisher: 'Nintendo / Camelot',
    year: 2004,
    genre: 'Sports / RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20Golf%20-%20Advance%20Tour.zip/Mario%20Golf%20-%20Advance%20Tour%20%28U%29.gba',
    description: 'Embark on a charming role-playing athletic adventure! Level up stats, challenge club maps, and meet Mario.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-arrow-trend-up',
    system: 'gba'
  },
  {
    id: 'mario_tennis_advance',
    title: 'Mario Tennis Advance - Power Tour',
    publisher: 'Nintendo / Camelot',
    year: 2005,
    genre: 'Sports / RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20Tennis%20Advance%20-%20Power%20Tour.zip/Mario%20Tennis%20Advance%20-%20Power%20Tour%20%28U%29.gba',
    description: 'Train to execute mystical physical super shots inside academy brackets to gain tennis championship ranks.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-baseball',
    system: 'gba'
  },
  {
    id: 'mario_party_advance',
    title: 'Mario Party Advance',
    publisher: 'Nintendo / Hudson',
    year: 2005,
    genre: 'Party / Board',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20Party%20Advance.zip/Mario%20Party%20Advance%20%28U%29.gba',
    description: 'Solve whimsical Shroom City resident quests in a digital Board game suited for handheld singleplay.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-dice',
    system: 'gba'
  },
  {
    id: 'mario_pinball_land',
    title: 'Mario Pinball Land',
    publisher: 'Nintendo / Fuse Games',
    year: 2004,
    genre: 'Pinball',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20Pinball%20Land.zip/Mario%20Pinball%20Land%20%28U%29.gba',
    description: 'Roll Mario directly as a pinball across five themed worlds to gather stars and rescue Peach from Bowser.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-circle-nodes',
    system: 'gba'
  },
  {
    id: 'mario_vs_donkey_kong',
    title: 'Mario vs. Donkey Kong',
    publisher: 'Nintendo',
    year: 2004,
    genre: 'Puzzle-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Mario%20vs.%20Donkey%20Kong.zip/Mario%20vs.%20Donkey%20Kong%20%28U%29%20%5B%21%5D.gba',
    description: 'Recover stolen Mini-Mario toys from Donkey Kong by maneuvering keys and switches across puzzling worlds.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-key',
    system: 'gba'
  },
  {
    id: 'kirby_nightmare_dreamland',
    title: 'Kirby - Nightmare in Dreamland',
    publisher: 'Nintendo / HAL Laboratory',
    year: 2002,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Kirby%20-%20Nightmare%20in%20Dreamland.zip/Kirby%20-%20Nightmare%20in%20Dreamland%20%28U%29%20%5B%21%5D.gba',
    description: 'Help Kirby retrieve the magical Star Rod from King Dedede to restore dreams to the residents of Dream Land.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-circle',
    system: 'gba'
  },
  {
    id: 'kirby_amazing_mirror',
    title: 'Kirby & The Amazing Mirror',
    publisher: 'Nintendo / HAL Laboratory',
    year: 2004,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Kirby%20%26%20The%20Amazing%20Mirror.zip/Kirby%20%26%20The%20Amazing%20Mirror%20%28U%29%20%5Bt1%5D.gba',
    description: 'Explore the Mirror World inside a gorgeous open-ended Metroidvania labyrinth, calling on multi-colored clone Kirbys for assistance.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-wand-magic-sparkles',
    system: 'gba'
  },
  {
    id: 'wario_land_4',
    title: 'Wario Land 4',
    publisher: 'Nintendo',
    year: 2001,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Wario%20Land%204.zip/Wario%20Land%204%20%28UE%29%20%5B%21%5D.gba',
    description: 'Dash, stomp, and grab treasure from a golden pyramid before the escape timer counts to zero.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-sack-dollar',
    system: 'gba'
  },
  {
    id: 'warioware_inc',
    title: 'WarioWare Inc.',
    publisher: 'Nintendo',
    year: 2003,
    genre: 'Party / Minigames',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/WarioWare%20Inc..zip/WarioWare%20Inc.%20%28U%29.gba',
    description: 'Execute hundreds of fast-paced, 5-second microgames inside of a chaotic split-second tournament barrage.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-cubes',
    system: 'gba'
  },
  {
    id: 'warioware_twisted',
    title: 'WarioWare - Twisted!',
    publisher: 'Nintendo',
    year: 2004,
    genre: 'Party / Minigames',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/WarioWare%20-%20Twisted%21.zip/WarioWare%20-%20Twisted%21%20%28U%29.gba',
    description: 'Spin and tilt your hand-held screen to complete unique action puzzles in of the best physical game ideas ever crafted.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-rotate-right',
    system: 'gba'
  },
  {
    id: 'ff_tactics_advance',
    title: 'Final Fantasy Tactics Advance',
    publisher: 'Squaresoft / Nintendo',
    year: 2003,
    genre: 'Tactical RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Final%20Fantasy%20Tactics%20Advance.zip/Final%20Fantasy%20Tactics%20Advance%20%28U%29%20%5B%21%5D.gba',
    description: 'Direct specialized clan divisions through battlefield maps while abiding by magical law rules outlined by judges.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-chess-board',
    system: 'gba'
  },
  {
    id: 'ff4_advance',
    title: 'Final Fantasy IV Advance',
    publisher: 'Squaresoft / Nintendo',
    year: 2005,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Final%20Fantasy%20IV%20Advance.zip/Final%20Fantasy%20IV%20Advance%20%28U%29.gba',
    description: 'The golden JRPG masterpiece complete with added post-game dungeon trials and customizable characters.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-fire',
    system: 'gba'
  },
  {
    id: 'ff5_advance',
    title: 'Final Fantasy V Advance',
    publisher: 'Squaresoft / Nintendo',
    year: 2006,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Final%20Fantasy%20V%20Advance.zip/Final%20Fantasy%20V%20Advance%20%28U%29.gba',
    description: 'Explore highly technical, deep JRPG job classification custom combinations inside of a marvelous fantasy layout.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-shield-halved',
    system: 'gba'
  },
  {
    id: 'ff6_advance',
    title: 'Final Fantasy VI Advance',
    publisher: 'Squaresoft / Nintendo',
    year: 2006,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Final%20Fantasy%20VI%20Advance.zip/Final%20Fantasy%20VI%20Advance%20%28U%29.gba',
    description: 'The definitive edition of the beloved 16-bit JRPG. Gather 14 heroes to destroy Kefka\'s apocalyptic world rule.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-crown',
    system: 'gba'
  },
  {
    id: 'ff_dawn_souls',
    title: 'Final Fantasy I & II - Dawn of Souls',
    publisher: 'Squaresoft / Nintendo',
    year: 2004,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Final%20Fantasy%20I%20%26%20II%20-%20Dawn%20of%20Souls.zip/Final%20Fantasy%20I%20%26%20II%20-%20Dawn%20of%20Souls%20%28U%29.gba',
    description: 'Play both classic NES blockbusters completely redrawn with convenient balance settings and extra dungeons.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-book-open',
    system: 'gba'
  },
  {
    id: 'fire_emblem_7',
    title: 'Fire Emblem',
    publisher: 'Nintendo / Intelligent Systems',
    year: 2003,
    genre: 'Tactical RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Fire%20Emblem.zip/Fire%20Emblem%20%28U%29%20%5B%21%5D.gba',
    description: 'Command soldiers inside dangerous permadeath turn-based combat battle zones to liberate Elibe territory with Eliwood and Lyn.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-shield-heart',
    system: 'gba'
  },
  {
    id: 'fire_emblem_sacred',
    title: 'Fire Emblem - The Sacred Stones',
    publisher: 'Nintendo / Intelligent Systems',
    year: 2004,
    genre: 'Tactical RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Fire%20Emblem%20-%20The%20Sacred%20Stones.zip/Fire%20Emblem%20-%20The%20Sacred%20Stones%20%28U%29.gba',
    description: 'Guide twin royalty heirs Ephraim and Eirika to push back demonic invasions across Magvel lands.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-gem',
    system: 'gba'
  },
  {
    id: 'fire_emblem_binding',
    title: 'Fire Emblem - Fuuin no Tsurugi (The Binding Blade)',
    publisher: 'Nintendo / Intelligent Systems',
    year: 2002,
    genre: 'Tactical RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Fire%20Emblem%20-%20Fuuin%20no%20Tsurugi.zip/Fire%20Emblem%20-%20Fuuin%20no%20Tsurugi%20%28J%29%20%5B%21%5D.gba',
    description: 'Play Roy\'s legendary Japanese exclusive fantasy adventure, translating beautiful sprite mechanics straight onto your screen.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-flag',
    system: 'gba'
  },
  {
    id: 'sonic_advance_1',
    title: 'Sonic Advance',
    publisher: 'Sega / Dimps',
    year: 2001,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Sonic%20Advance.zip/Sonic%20Advance%20%28U%29%20%5B%21%5D.gba',
    description: 'Dash past loops and loops of mechanical obstacle hazards as Sonic, Tails, Knuckles, or Amy Rose.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-gauge-high',
    system: 'gba'
  },
  {
    id: 'sonic_advance_2',
    title: 'Sonic Advance 2',
    publisher: 'Sega / Dimps',
    year: 2002,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Sonic%20Advance%202.zip/Sonic%20Advance%202%20%28U%29%20%28M6%29%20%5B%21%5D.gba',
    description: 'Speed actions scaled to the extreme! Accelerate and jump seamlessly through vast platforms with Cream the Rabbit.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-bolt',
    system: 'gba'
  },
  {
    id: 'sonic_advance_3',
    title: 'Sonic Advance 3',
    publisher: 'Sega / Dimps',
    year: 2004,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Sonic%20Advance%203.zip/Sonic%20Advance%203%20%28U%29%20%28M6%29.gba',
    description: 'Combine character couples to unlock special movement speed tags and double combat capabilities.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-people-group',
    system: 'gba'
  },
  {
    id: 'sonic_battle',
    title: 'Sonic Battle',
    publisher: 'Sega',
    year: 2003,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Sonic%20Battle.zip/Sonic%20Battle%20%28U%29%20%28M6%29.gba',
    description: 'Engage in 3D arena battles with Sonic characters, customizing Emerl\'s skills to unleash custom combo attacks.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-hand-fist',
    system: 'gba'
  },
  {
    id: 'sonic_pinball_party',
    title: 'Sonic Pinball Party',
    publisher: 'Sega',
    year: 2003,
    genre: 'Pinball',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Sonic%20Pinball%20Party.zip/Sonic%20Pinball%20Party%20%28U%29%20%28M6%29.gba',
    description: 'Battle Dr. Eggman across vibrant pinball boards referencing beloved Sonic, Nights, and Samba de Amigo universes.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-circle-dot',
    system: 'gba'
  },
  {
    id: 'megaman_bn_1',
    title: 'Mega Man Battle Network',
    publisher: 'Capcom',
    year: 2001,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Megaman%20Battle%20Network.zip/Megaman%20Battle%20Network%20%28U%29%20%5B%21%5D.gba',
    description: 'Plug Lan into digital cyberspace to guide MegaMan.EXE in action-card micro tactical battle zones.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-network-wired',
    system: 'gba'
  },
  {
    id: 'megaman_bn_2',
    title: 'Mega Man Battle Network 2',
    publisher: 'Capcom',
    year: 2001,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Megaman%20Battle%20Network%202.zip/Megaman%20Battle%20Network%202%20%28U%29%20%5B%21%5D.gba',
    description: 'Confront net-terrorism with advanced customization slots and elements-based physical transformations.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-layer-group',
    system: 'gba'
  },
  {
    id: 'megaman_bn_3',
    title: 'Mega Man Battle Network 3',
    publisher: 'Capcom',
    year: 2002,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Megaman%20Battle%20Network%203.zip/Megaman%20Battle%20Network%203%20-%20Blue%20Version%20%28U%29%20%5B%21%5D.gba',
    description: 'Uncover the final technical secrets of the WWW net alliance in this highly-rated strategic network RPG installment.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-star',
    system: 'gba'
  },
  {
    id: 'megaman_zero',
    title: 'Mega Man Zero',
    publisher: 'Capcom / Inti Creates',
    year: 2002,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Megaman%20Zero.zip/Megaman%20Zero%20%28U%29.gba',
    description: 'Guide Zero through high-stakes, fast-paced action-platformer battles with gun and saber configurations.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-biohazard',
    system: 'gba'
  },
  {
    id: 'megaman_zero2',
    title: 'Mega Man Zero 2',
    publisher: 'Capcom / Inti Creates',
    year: 2003,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Megaman%20Zero%202.zip/Megaman%20Zero%202%20%28U%29.gba',
    description: 'Upgrade your resistance weapons arsenal and execute technical platforming counter combos to secure ranking points.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-shield-heart',
    system: 'gba'
  },
  {
    id: 'king_hearts_chain',
    title: 'Kingdom Hearts - Chain of Memories',
    publisher: 'Squaresoft / Disney',
    year: 2004,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Kingdom%20Hearts%20-%20Chain%20of%20Memories.zip/Kingdom%20Hearts%20-%20Chain%20of%20Memories%20%28U%29.gba',
    description: 'Ascend Castle Oblivion using an innovative card combat system. Discover hidden memories alongside Sora, Donald, and Goofy.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-heart',
    system: 'gba'
  },
  {
    id: 'yugioh_eternal_duelist',
    title: 'Yu-Gi-Oh! - The Eternal Duelist Soul',
    publisher: 'Konami',
    year: 2002,
    genre: 'Card Battle',
    romUrl: 'https://archive.org/download/GameboyAdvanceRomCollectionByGhostware/Yu-Gi-Oh%21%20-%20The%20Eternal%20Duelist%20Soul.zip/Yu-Gi-Oh%21%20-%20The%20Eternal%20Duelist%20Soul%20%28U%29%20%5B%21%5D.gba',
    description: 'Duel against classic Yu-Gi-Oh! characters, construct your deck with over 800 cards, and conquer tournament matches to prove you are the ultimate Duelist.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-clone',
    system: 'gba'
  }
  */
]