import { Game } from "./types";

export const N64_GAMES: Game[] = [
  // --- NINTENDO 64 GAMES ---
  {
    id: 'super_mario_64',
    title: 'Super Mario 64',
    publisher: 'Nintendo',
    year: 1996,
    genre: '3D Platformer',
    romUrl: 'games/Super Mario 64 (USA).z64',
    description: "The definitive blueprint for 3D platformers. Explore Princess Peach's castle, jump into magical paintings, collect Power Stars, and save Peach from Bowser.",
    gradientClass: 'cover-gradient-2',
    icon: 'fa-crown',
    coverImage: 'covers/super-mario-64-logo.png',
    system: 'n64'
  },
  {
    id: 'zelda_oot',
    title: 'The Legend of Zelda: Ocarina of Time',
    publisher: 'Nintendo',
    year: 1998,
    genre: 'Action-Adventure',
    romUrl: 'games/Legend of Zelda, The - Ocarina of Time (USA).z64',
    description: 'An epic fantasy masterpiece. Journey through time, traverse sprawling Hyrule landscape, and solve ancient temples to stop Ganondorf.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-shield-halved',
    system: 'n64'
  },
  {
    id: 'goldeneye_007',
    title: 'GoldenEye 007',
    publisher: 'Nintendo / Rare',
    year: 1997,
    genre: 'First-Person Shooter',
    romUrl: 'games/007 - GoldenEye (USA).z64',
    description: 'The legendary first-person shooter that revolutionized console multiplayer. Play as James Bond, navigate through action-packed missions, and engage in split-screen multiplayer matches.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-user-secret',
    coverImage: 'covers/goldeneye007.jpg',
    system: 'n64'
  },
  {
    id: 'mario_kart_64',
    title: 'Mario Kart 64',
    publisher: 'Nintendo',
    year: 1996,
    genre: 'Kart Racing',
    romUrl: 'games/Mario Kart 64 (USA).z64',
    description: 'Race past competitor players using special items to cross the finish line in a series of colorful tracks like Rainbow Road.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-flag-checkered',
    system: 'n64'
  },
  {
    id: 'super_smash_bros',
    title: 'Super Smash Bros.',
    publisher: 'Nintendo / HAL Laboratory',
    year: 1999,
    genre: 'Fighting / Brawler',
    romUrl: 'games/Super Smash Bros. (USA).z64',
    description: 'The classic crossover fighting game. Select iconic Nintendo characters like Mario, Link, Samus, and Pikachu and fight to knock opponents off the stage.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-hand-fist',
    coverImage: 'covers/super-smash-bros-64.webp',
    system: 'n64'
  },
  /*
  {
    id: 'zelda_mm',
    title: "The Legend of Zelda: Majora's Mask",
    publisher: 'Nintendo',
    year: 2000,
    genre: 'Action-Adventure',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Legend%20of%20Zelda%2C%20The%20-%20Majora%27s%20Mask%20%28USA%29.z64',
    description: 'Solve the mysteries of Termina and halt a looming catastrophe within 3 days using various masks that offer unique abilities.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-mask',
    system: 'n64'
  },
  {
    id: 'banjo_kazooie',
    title: 'Banjo-Kazooie',
    publisher: 'Rare / Nintendo',
    year: 1998,
    genre: '3D Platformer',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Banjo-Kazooie%20%28USA%29.z64',
    description: 'Join a bear and a bird duo as they collect puzzles and musical notes to defeat the witch Gruntilda and save Banjo\'s sister.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-feather',
    system: 'n64'
  },
  {
    id: 'donkey_kong_64',
    title: 'Donkey Kong 64',
    publisher: 'Rare / Nintendo',
    year: 1999,
    genre: '3D Platformer',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Donkey%20Kong%2064%20%28USA%29.z64',
    description: 'Take control of the DK crew and explore King K. Rool\'s islands to retrieve his legendary banana hoard in this collect-a-thon platformer.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-egg',
    system: 'n64'
  },
  {
    id: 'perfect_dark',
    title: 'Perfect Dark',
    publisher: 'Rare / Nintendo',
    year: 2000,
    genre: 'First-Person Shooter',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Perfect%20Dark%20%28USA%29.z64',
    description: 'Control secret agent Joanna Dark as she uncovers a vast conspiracy between astronomical alien factions and private corporations.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-crosshairs',
    system: 'n64'
  },
  {
    id: 'mario_party_1',
    title: 'Mario Party',
    publisher: 'Nintendo / Hudson',
    year: 1998,
    genre: 'Party / Board Game',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Mario%20Party%20%28USA%29.z64',
    description: 'The star-collecting digital board game that launched a legacy of hilarious friendship-testing multiplayer mini-game tournaments.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-chess-board',
    system: 'n64'
  },
  {
    id: 'mario_party_2',
    title: 'Mario Party 2',
    publisher: 'Nintendo / Hudson',
    year: 1999,
    genre: 'Party / Board Game',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Mario%20Party%202%20%28USA%29.z64',
    description: 'The fan-favorite successor featuring themed costume maps and refined item additions to elevate board-game sabotage to new heights.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-hat-wizard',
    system: 'n64'
  },
  {
    id: 'mario_party_3',
    title: 'Mario Party 3',
    publisher: 'Nintendo / Hudson',
    year: 2000,
    genre: 'Party / Board Game',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Mario%20Party%203%20%28USA%29.z64',
    description: 'Collect Milennial Stars and duel in intense arena encounters as you challenge friends to the third board game installment of the series.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-star',
    system: 'n64'
  },
  {
    id: 'paper_mario',
    title: 'Paper Mario',
    publisher: 'Nintendo / Intelligent Systems',
    year: 2000,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Paper%20Mario%20%28USA%29.z64',
    description: 'A charming RPG set in a colorful papercraft-inspired Mushroom Kingdom, blending classic turn-based battles with reflex-driven execution.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-book-open',
    system: 'n64'
  },
  {
    id: 'pokemon_stadium',
    title: 'Pokémon Stadium',
    publisher: 'Nintendo',
    year: 1999,
    genre: 'Strategy / Battler',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Pokemon%20Stadium%20%28USA%29.z64',
    description: 'Immerse yourself in spectacular 3D Pokémon battles, strategy championships, and a delightful sandbox pool of retro mini-games.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-gamepad',
    system: 'n64'
  },
  {
    id: 'pokemon_stadium_2',
    title: 'Pokémon Stadium 2',
    publisher: 'Nintendo',
    year: 2000,
    genre: 'Strategy / Battler',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Pokemon%20Stadium%202%20%28USA%29.z64',
    description: 'Elevate tactics to Generation II with Gold and Silver companions, advanced technical challenges, and brand new additions.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-bolt',
    system: 'n64'
  },
  {
    id: 'pokemon_snap',
    title: 'Pokémon Snap',
    publisher: 'Nintendo',
    year: 1999,
    genre: 'Simulation',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Pokemon%20Snap%20%28USA%29.z64',
    description: 'Go on a wild on-rails photographic safari excursion to map, entice, and capture premium pictures of Pokémon in wild environments.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-camera',
    system: 'n64'
  },
  {
    id: 'star_fox_64',
    title: 'Star Fox 64',
    publisher: 'Nintendo',
    year: 1997,
    genre: 'On-Rails Shooter',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Star%20Fox%2064%20%28USA%29.z64',
    description: 'Pilot the Arwing with Fox, Falco, Peppy, and Slippy to defend the Lylat System from Andross forces in this cinematic sci-fi adventure.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-jet-fighter',
    system: 'n64'
  },
  {
    id: 'diddy_kong_racing',
    title: 'Diddy Kong Racing',
    publisher: 'Rare / Nintendo',
    year: 1997,
    genre: 'Kart Racing',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Diddy%20Kong%20Racing%20%28USA%29%20%28En%2CFr%29.z64',
    description: "An adventure-style racing game. Drive cars, planes, and hovercrafts to defeat the intergalactic sorcerer Wizpig and save Timber's island.",
    gradientClass: 'cover-gradient-4',
    icon: 'fa-car',
    coverImage: 'covers/diddy-kong-racing.jpg',
    system: 'n64'
  },
  {
    id: 'conkers_bad_fur_day',
    title: "Conker's Bad Fur Day",
    publisher: 'Rare / THQ',
    year: 2001,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Conker%27s%20Bad%20Fur%20Day%20%28USA%29.z64',
    description: 'Interact with quirky characters, solve puzzles, and engage in crude humor in this mature, action-packed story of a red squirrel named Conker.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-paw',
    coverImage: 'covers/Conkers-bad-fur-day.jpg',
    system: 'n64'
  },
  {
    id: 'rayman_2',
    title: 'Rayman 2: The Great Escape',
    publisher: 'Ubisoft',
    year: 1999,
    genre: '3D Platformer',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Rayman%202%20-%20The%20Great%20Escape%20%28USA%29%20%28En%2CFr%2CDe%2CEs%2CIt%29.z64',
    description: 'Restore peace to Glade of Dreams and free captured slaves by fighting back Robo-Pirates led by Admiral Razorbeard.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-hand',
    system: 'n64'
  },
  {
    id: 'resident_evil_2',
    title: 'Resident Evil 2',
    publisher: 'Capcom',
    year: 1999,
    genre: 'Survival Horror',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Resident%20Evil%202%20%28USA%29.z64',
    description: 'Survive the viral zombie outbreak in Raccoon City as rookie cop Leon Kennedy or college student Claire Redfield.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-skull',
    system: 'n64'
  },
  {
    id: 'turok_dh',
    title: 'Turok: Dinosaur Hunter',
    publisher: 'Acclaim',
    year: 1997,
    genre: 'First-Person Shooter',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Turok%20-%20Dinosaur%20Hunter%20%28USA%29.z64',
    description: 'Battle dinosaurs, cyborgs, and prehistoric beasts to protect the barrier separating Earth from the Lost Land as the warrior Turok.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-dragon',
    system: 'n64'
  },
  {
    id: 'star_wars_shadows',
    title: 'Star Wars: Shadows of the Empire',
    publisher: 'LucasArts',
    year: 1996,
    genre: 'Action Shooter',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Star%20Wars%20-%20Shadows%20of%20the%20Empire%20%28USA%29.z64',
    description: 'Control mercenary Dash Rendar following the events of The Empire Strikes Back, participating in space and planetary vehicular battles.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-jedi',
    system: 'n64'
  },
  {
    id: 'wave_race_64',
    title: 'Wave Race 64',
    publisher: 'Nintendo',
    year: 1996,
    genre: 'Water Racing',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Wave%20Race%2064%20%28USA%29.z64',
    description: 'Race jet skis in dynamic water physics, slalom boundaries, and executing tricky maneuvers across wavy shores.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-water',
    system: 'n64'
  },
  {
    id: 'f_zero_x',
    title: 'F-Zero X',
    publisher: 'Nintendo',
    year: 1998,
    genre: 'Futuristic Racing',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/F-Zero%20X%20%28USA%29.z64',
    description: 'Experience supersonic speeds running on 3D looping cylinder tunnels with 30 pilots combating to declare futuristic championship victories.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-rocket',
    system: 'n64'
  },

    {
    id: 'kirby_64',
    title: 'Kirby 64: The Crystal Shards',
    publisher: 'Nintendo / HAL Laboratory',
    year: 2000,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Kirby%2064%20-%20The%20Crystal%20Shards%20%28USA%29.z64',
    description: 'Traverse 2.5D landscapes, swallow enemies, and combine differing power capabilities to unlock premium ability combinations during search journeys.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-circle',
    system: 'n64'
  },
  {
    id: 'tony_hawk_ps',
    title: "Tony Hawk's Pro Skater",
    publisher: 'Neversoft / Activision',
    year: 1999,
    genre: 'Extreme Sports',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Tony%20Hawk%27s%20Pro%20Skater%20%28USA%29.z64',
    description: 'Execute kickflips, grinds, and signature combos with skate legend professionals set to iconic soundtracks.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-person-biking',
    system: 'n64'
  },
  {
    id: 'mario_tennis',
    title: 'Mario Tennis',
    publisher: 'Nintendo / Camelot',
    year: 2000,
    genre: 'Sports',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Mario%20Tennis%20%28USA%29.z64',
    description: 'Face off in premium Mushroom Kingdom tennis matches equipped with slice, lobby, and standard shot actions.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-baseball',
    system: 'n64'
  },
  {
    id: 'harvest_moon_64',
    title: 'Harvest Moon 64',
    publisher: 'Natsume / Toy Box',
    year: 1999,
    genre: 'Farming Simulation',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Harvest%20Moon%2064%20%28USA%29.z64',
    description: 'Restore your grandfather\'s farm, grow crops, raise livestock, and bond with local villagers in this historic sandbox classic.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-cow',
    system: 'n64'
  },
  {
    id: 'jet_force_gemini',
    title: 'Jet Force Gemini',
    publisher: 'Rare / Nintendo',
    year: 1999,
    genre: 'Action Shooter',
    romUrl: 'https://archive.org/download/pack-roms-nintendo-64-eu-us-jap/Jet%20Force%20Gemini%20%28USA%29.z64',
    description: 'Join space agents Juno, Vela, and their mascot dog Lupus to eliminate tyrannical insectoid army threats ruling the cosmos.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-bug',
    system: 'n64'
  },
  */
]