import { Game } from "./types";

export const SNES_GAMES: Game[] = [
  // --- SUPER NINTENDO (SNES) GAMES ---
  {
    id: 'super_mario_world',
    title: 'Super Mario World',
    publisher: 'Nintendo',
    year: 1990,
    genre: '2D Platformer',
    romUrl: 'games/mworld.sfc',
    description: 'Help Mario and Luigi rescue Princess Toadstool and defeat the evil Bowser in Dinosaur Land, featuring the debut of Yoshi!',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-egg',
    system: 'snes'
  },
  {
    id: 'super_mario_kart',
    title: 'Super Mario Kart',
    publisher: 'Nintendo',
    year: 1992,
    genre: 'Kart Racing',
    romUrl: 'games/mkart.sfc',
    description: 'The grandfather of kart racing! Race against iconic Mushroom Kingdom characters in challenging circuits and weapon-filled battles.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-flag-checkered',
    system: 'snes'
  },
  
  {
    id: 'super_metroid',
    title: 'Super Metroid',
    publisher: 'Nintendo',
    year: 1994,
    genre: 'Metroidvania',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Metroid%20%28Japan%2C%20USA%29%20%28En%2CJa%29.zip',
    description: 'Control bounty hunter Samus Aran as she explores planet Zebes to retrieve a stolen Metroid hatchling from Ridley and the Space Pirates.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-jet-fighter',
    system: 'snes'
  },
  {
    id: 'zelda_alttp',
    title: 'The Legend of Zelda: A Link to the Past',
    publisher: 'Nintendo',
    year: 1991,
    genre: 'Action-Adventure',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20to%20the%20Past%20%28USA%29.zip',
    description: 'Embark on an epic journey through Hyrule, traversing between the Light and Dark Worlds to defeat Ganon and save the maidens.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-shield-halved',
    system: 'snes'
  },
  {
    id: 'super_mario_rpg',
    title: 'Super Mario RPG: Legend of the Seven Stars',
    publisher: 'Nintendo / Squaresoft',
    year: 1996,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Mario%20RPG%20-%20Legend%20of%20the%20Seven%20Stars%20%28USA%29.zip',
    description: 'Join forces with Bowser, Peach, and new friends Mallow and Geno to retrieve the seven Star Pieces and mend the Star Road.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-star-of-david',
    system: 'snes'
  },
  {
    id: 'yoshis_island',
    title: "Super Mario World 2: Yoshi's Island",
    publisher: 'Nintendo',
    year: 1995,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Mario%20World%202%20-%20Yoshi%27s%20Island%20%28USA%29.zip',
    description: 'Guaranteed to pull at your heartstrings. Guide Baby Mario safely across Yoshi\'s Island and defeat Baby Bowser.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-dinosaur',
    system: 'snes'
  },
  {
    id: 'super_castlevania_iv',
    title: 'Super Castlevania IV',
    publisher: 'Konami',
    year: 1991,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Castlevania%20IV%20%28USA%29.zip',
    description: 'Control Simon Belmont with his multi-directional whip as he climbs and fights through Dracula\'s daunting gothic castle.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-wand-magic-sparkles',
    system: 'snes'
  },
  {
    id: 'super_ghouls_n_ghosts',
    title: "Super Ghouls'n Ghosts",
    publisher: 'Capcom',
    year: 1991,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Ghouls%27n%20Ghosts%20%28USA%29.zip',
    description: 'Guide Arthur on a grueling adventure through hordes of ghouls and monsters to rescue Princess Guinevere.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-ghost',
    system: 'snes'
  },
  {
    id: 'donkey_kong_country',
    title: 'Donkey Kong Country',
    publisher: 'Nintendo / Rare',
    year: 1994,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Donkey%20Kong%20Country%20%28USA%29.zip',
    description: 'Navigate the jungle, mine carts, and treetops with Donkey Kong and Diddy Kong to retrieve their stolen banana hoard from King K. Rool.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-shrimp',
    system: 'snes'
  },
  {
    id: 'donkey_kong_country_2',
    title: "Donkey Kong Country 2: Diddy's Kong Quest",
    publisher: 'Nintendo / Rare',
    year: 1995,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Donkey%20Kong%20Country%202%20-%20Diddy%27s%20Kong%20Quest%20%28USA%29%20%28En%2CFr%29.zip',
    description: 'Help Diddy and Dixie Kong search for the captured Donkey Kong on Crocodile Isle in of the highest rated 2D platformers ever generated.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-paw',
    system: 'snes'
  },
  {
    id: 'donkey_kong_country_3',
    title: "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
    publisher: 'Nintendo / Rare',
    year: 1996,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Donkey%20Kong%20Country%203%20-%20Dixie%20Kong%27s%20Double%20Trouble%21%20%28USA%29%20%28En%2CFr%29.zip',
    description: 'Join Dixie and Kiddy Kong as they explore the Northern Kremisphere to find both Donkey Kong and Diddy Kong after their disappearance.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-baby',
    system: 'snes'
  },
  {
    id: 'chrono_trigger',
    title: 'Chrono Trigger',
    publisher: 'Squaresoft',
    year: 1995,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Chrono%20Trigger%20%28USA%29.zip',
    description: 'A masterpiece RPG featuring a revolutionary battle system and a gripping time-travel story spanning from prehistory to the end of time.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-hourglass-half',
    system: 'snes'
  },
  {
    id: 'final_fantasy_ii',
    title: 'Final Fantasy II (IV)',
    publisher: 'Squaresoft',
    year: 1991,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Final%20Fantasy%20II%20%28USA%29.zip',
    description: 'Follow the dark knight Cecil as he rebels against his kingdom and gathers allies to save the world from an ancient evil.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-fire-flame-curved',
    system: 'snes'
  },
  {
    id: 'final_fantasy_iii',
    title: 'Final Fantasy III (VI)',
    publisher: 'Squaresoft',
    year: 1994,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Final%20Fantasy%20III%20%28USA%29.zip',
    description: 'A breathtaking epic revolving around rebellion, magic, steampunk machinery, and an unforgettable jester villain named Kefka.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-mask-face',
    system: 'snes'
  },
  {
    id: 'secret_of_mana',
    title: 'Secret of Mana',
    publisher: 'Squaresoft',
    year: 1993,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Secret%20of%20Mana%20%28USA%29.zip',
    description: 'Embark on a colorful real-time combat action-RPG journey following three heroes trying to stop an empire using the power of Mana.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-leaf',
    system: 'snes'
  },
  {
    id: 'earthbound',
    title: 'EarthBound',
    publisher: 'Nintendo',
    year: 1994,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/EarthBound%20%28USA%29.zip',
    description: 'Set in a satirical take on modern Americana. Guide Ness and friends to gather melodies and stop the cosmic destroyer Giygas.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-baseball-bat-ball',
    system: 'snes'
  },
  {
    id: 'street_fighter_ii_turbo',
    title: 'Street Fighter II Turbo',
    publisher: 'Capcom',
    year: 1993,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Street%20Fighter%20II%20Turbo%20%28USA%29.zip',
    description: 'The gold standard arcade fighting experience. Speed-boosted, introducing refined combos, and playable with eight unique combatants.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-hand-fist',
    system: 'snes'
  },
  {
    id: 'super_street_fighter_ii',
    title: 'Super Street Fighter II',
    publisher: 'Capcom',
    year: 1994,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Street%20Fighter%20II%20%28USA%29.zip',
    description: 'Introducing four brand new challengers: Cammy, Dee Jay, Fei Long, and T. Hawk for extreme final round tournaments.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-users',
    system: 'snes'
  },
  {
    id: 'mortal_kombat_ii',
    title: 'Mortal Kombat II',
    publisher: 'Acclaim / Midway',
    year: 1993,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Mortal%20Kombat%20II%20%28USA%29.zip',
    description: 'Wreak havoc in Outworld with refined Fatalities, Babilities, and stage hazards in this brutal competitive fighter.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-skull-crossbones',
    system: 'snes'
  },
  {
    id: 'ultimate_mortal_kombat_3',
    title: 'Ultimate Mortal Kombat 3',
    publisher: 'Acclaim / Midway',
    year: 1995,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Ultimate%20Mortal%20Kombat%203%20%28USA%29.zip',
    description: 'The final, expanded iteration of MK3 with returning favorites, secret warriors, and intense tournament-style competitive brackets.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-crown',
    system: 'snes'
  },
  {
    id: 'tmnt_iv_turtles_in_time',
    title: 'Teenage Mutant Ninja Turtles IV: Turtles in Time',
    publisher: 'Konami',
    year: 1992,
    genre: 'Beat \'Em Up',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Teenage%20Mutant%20Ninja%20Turtles%20IV%20-%20Turtles%20in%20Time%20%28USA%29.zip',
    description: 'Fight back Shredder\'s forces across various periods of history in the premier cooperative side-scrolling TMNT brawler.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-pizza-slice',
    system: 'snes'
  },
  {
    id: 'contra_iii_alien_wars',
    title: 'Contra III: The Alien Wars',
    publisher: 'Konami',
    year: 1992,
    genre: 'Run & Gun',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Contra%20III%20-%20The%20Alien%20Wars%20%28USA%29.zip',
    description: 'Arm yourself to fight off an alien invasion in intense, side-scrolling, high-difficulty run-and-gun combat levels.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-shield-heart',
    system: 'snes'
  },
  {
    id: 'super_punch_out',
    title: 'Super Punch-Out!!',
    publisher: 'Nintendo',
    year: 1994,
    genre: 'Sports / Boxing',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Punch-Out%21%21%20%28USA%29.zip',
    description: 'Climb the World Video Boxing Association ladder, executing precise dodging, counterattacks, and rapid-fire punches.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-square-plus',
    system: 'snes'
  },
  {
    id: 'star_fox',
    title: 'Star Fox',
    publisher: 'Nintendo',
    year: 1993,
    genre: 'Shoot \'Em Up',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Star%20Fox%20%28USA%29.zip',
    description: 'The pioneering 3D polygonal shooter utilizing the Super FX chip. Fly alongside McCloud and crew to defeat Andross.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-rocket',
    system: 'snes'
  },
  {
    id: 'f_zero',
    title: 'F-Zero',
    publisher: 'Nintendo',
    year: 1990,
    genre: 'Futuristic Racing',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/F-Zero%20%28USA%29.zip',
    description: 'Navigate treacherous futuristic loops and speed zones in high-speed Mode 7 physics racing tournaments.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-gauge-high',
    system: 'snes'
  },
  {
    id: 'illusion_of_gaia',
    title: 'Illusion of Gaia',
    publisher: 'Nintendo / Quintet',
    year: 1993,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Illusion%20of%20Gaia%20%28USA%29.zip',
    description: 'Control Will as he transforms into different legendary warriors on a globetrotting quest to save Earth from a dark comet.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-earth-americas',
    system: 'snes'
  },
  {
    id: 'secret_of_evermore',
    title: 'Secret of Evermore',
    publisher: 'Squaresoft',
    year: 1995,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Secret%20of%20Evermore%20%28USA%29.zip',
    description: 'Follow a boy and his shape-shifting dog companion as they are transported through different prehistoric, antiquarian, and gothic periods.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-paw',
    system: 'snes'
  },
  {
    id: 'breath_of_fire_ii',
    title: 'Breath of Fire II',
    publisher: 'Capcom',
    year: 1994,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Breath%20of%20Fire%20II%20%28USA%29.zip',
    description: 'Follow Ryu, who belongs to the dragon clan, on an expansive classic JRPG adventure to solve his family\'s mysterious past.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-dragon',
    system: 'snes'
  },
  {
    id: 'kirby_super_star',
    title: 'Kirby Super Star',
    publisher: 'Nintendo / HAL Laboratory',
    year: 1996,
    genre: '2D Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Kirby%20Super%20Star%20%28USA%29.zip',
    description: 'Eight unique sub-games in one package! Swallowing copying capabilities, calling cooperators, and taking down King Dedede.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-face-laugh',
    system: 'snes'
  },
  {
    id: 'super_bomberman',
    title: 'Super Bomberman',
    publisher: 'Hudson Soft',
    year: 1993,
    genre: 'Action / Strategy',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Super%20Bomberman%20%28USA%29.zip',
    description: 'Place bombs, explode destructible grids, collect power-ups, and square off against friends in intense arena showdown battles.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-bomb',
    system: 'snes'
  },
  {
    id: 'actraiser',
    title: 'ActRaiser',
    publisher: 'Enix / Quintet',
    year: 1990,
    genre: 'Action / Simulation',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/ActRaiser%20%28USA%29.zip',
    description: 'Breathtakingly unique. Toggle between high-stakes action platforming battles and a peaceful colony management simulator perspective.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-cloud-sun',
    system: 'snes'
  },
  {
    id: 'soul_blazer',
    title: 'Soul Blazer',
    publisher: 'Enix / Quintet',
    year: 1992,
    genre: 'Action-RPG',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Soul%20Blazer%20%28USA%29.zip',
    description: 'Play as a celestial messenger of the Deity to defeat Deathtoll forces and liberate trapped creature souls across ancient shrines.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-sun',
    system: 'snes'
  },
  {
    id: 'ogre_battle',
    title: 'Ogre Battle: The March of the Black Queen',
    publisher: 'Enix / Quest',
    year: 1993,
    genre: 'Tactical RPG',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Ogre%20Battle%20-%20The%20March%20of%20the%20Black%20Queen%20%28USA%29.zip',
    description: 'Lead a liberation army with tactical planning, recruiting units, and managing alignment across a complex tarot-card driven storyline.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-layer-group',
    system: 'snes'
  },
  {
    id: 'lufia_ii',
    title: 'Lufia II: Rise of the Sinistrals',
    publisher: 'Natsume / Neverland',
    year: 1995,
    genre: 'Role-Playing Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Lufia%20II%20-%20Rise%20of%20the%20Sinistrals%20%28USA%29.zip',
    description: 'Explore dungeon puzzles, seek out magical equipment, and challenge the almighty Sinistrals to save humanity.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-gem',
    system: 'snes'
  },
  {
    id: 'demons_crest',
    title: "Demon's Crest",
    publisher: 'Capcom',
    year: 1994,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Demon%27s%20Crest%20%28USA%29.zip',
    description: 'Guide the gargoyle Firebrand as he searches for magical elemental crests to seek vengeance against his nemesis Phalanx.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-fire',
    system: 'snes'
  },
  {
    id: 'wild_guns',
    title: 'Wild Guns',
    publisher: 'Natsume',
    year: 1994,
    genre: 'Sci-Fi Shooter',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Wild%20Guns%20%28USA%29.zip',
    description: 'Enjoy a wild steampunk-western gallery shooter! Dodge crossfire, swing lasso tools, and gun down giant biomechanical bosses.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-gun',
    system: 'snes'
  },
  {
    id: 'sunset_riders',
    title: 'Sunset Riders',
    publisher: 'Konami',
    year: 1993,
    genre: 'Run & Gun',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Sunset%20Riders%20%28USA%29.zip',
    description: 'Hunt down outlaws for bounty rewards in a fast-paced, colorful, bullet-filled cooperative run-and-gun wild-western arcade classic.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-dollar-sign',
    system: 'snes'
  },
  {
    id: 'zombies_ate_my_neighbors',
    title: 'Zombies Ate My Neighbors',
    publisher: 'Konami / LucasArts',
    year: 1993,
    genre: 'Action Shooter',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Zombies%20Ate%20My%20Neighbors%20%28USA%29.zip',
    description: 'Run through neighborhoods, malls, and castles saving innocent civilians from various cult classic horror movie monsters.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-biohazard',
    system: 'snes'
  },
  {
    id: 'earthworm_jim',
    title: 'Earthworm Jim',
    publisher: 'Playmates / Shiny',
    year: 1994,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Earthworm%20Jim%20%28USA%29.zip',
    description: 'Pilot an ultra-high-tech suit in this wacky surrealist platformer as a worm blasting through bizarre intergalactic planets.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-worm',
    system: 'snes'
  },
  {
    id: 'blackthorne',
    title: 'Blackthorne',
    publisher: 'Interplay / Blizzard',
    year: 1994,
    genre: 'Cinematic Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Blackthorne%20%28USA%29.zip',
    description: 'Control Kyle Vlaros using tactical cover, shotgun back-blasts, and athletic leaps to liberate planet Tuul from monsters.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-user-ninja',
    system: 'snes'
  },
  {
    id: 'flashback',
    title: 'Flashback: The Quest for Identity',
    publisher: "U.S. Gold / Delphine Entertainment",
    year: 1993,
    genre: 'Cinematic Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Flashback%20-%20The%20Quest%20for%20Identity%20%28USA%29%20%28En%2CFr%2CDe%29.zip',
    description: 'Explore immersive platforms as Conrad while trying to regain vanished memories and reveal hidden alien impostors.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-mask',
    system: 'snes'
  },
  {
    id: 'another_world',
    title: 'Out of this World (Another World)',
    publisher: 'Interplay',
    year: 1992,
    genre: 'Cinematic Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Out%20of%20this%20World%20%28USA%29.zip',
    description: 'Escape traps, befriend aliens, and solve puzzles across a mysterious planet after a nuclear lab experiment goes wrong.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-meteor',
    system: 'snes'
  },
  {
    id: 'prince_of_persia',
    title: 'Prince of Persia',
    publisher: 'Konami',
    year: 1992,
    genre: 'Cinematic Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Prince%20of%20Persia%20%28USA%29.zip',
    description: 'Escape castle dungeons, defeat guard patrols, avoid blade traps, and save the princess within 120 minutes.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-hourglass-start',
    system: 'snes'
  },
  {
    id: 'simcity',
    title: 'SimCity',
    publisher: 'Nintendo / Maxis',
    year: 1991,
    genre: 'City Simulator',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/SimCity%20%28USA%29.zip',
    description: 'Build power plants, layout roads, organize zoning, and direct disaster plans to build an organized retro metropolitan city.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-city',
    system: 'snes'
  },
  {
    id: 'pilotwings',
    title: 'Pilotwings',
    publisher: 'Nintendo',
    year: 1990,
    genre: 'Flight Simulation',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Pilotwings%20%28USA%29.zip',
    description: 'Earn aviation licenses by pilot training skydiving, hang gliders, light aircrafts, and rocket belts.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-wind',
    system: 'snes'
  },
  {
    id: 'uniracers',
    title: 'Uniracers (Unirally)',
    publisher: 'Nintendo / DMA Design',
    year: 1994,
    genre: 'Racing / Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Uniracers%20%28USA%29.zip',
    description: 'Guide unmanned unicycles down tricky tracks, executing twists and loops to boost and accelerate to victory.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-wheelchair',
    system: 'snes'
  },
  {
    id: 'rock_n_roll_racing',
    title: "Rock n' Roll Racing",
    publisher: 'Interplay / Blizzard',
    year: 1993,
    genre: 'Combat Racing',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Rock%20n%27%20Roll%20Racing%20%28USA%29.zip',
    description: 'Inundate racetracks with heavy metal music, lasers, and custom armed space karts in this top-down classic fighter-racer.',
    gradientClass: 'cover-gradient-3',
    icon: 'fa-guitar',
    system: 'snes'
  },
  {
    id: 'killer_instinct',
    title: 'Killer Instinct',
    publisher: 'Nintendo / Rare / Midway',
    year: 1995,
    genre: 'Fighting Game',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Killer%20Instinct%20%28USA%29.zip',
    description: 'Deliver record breaking continuous combos, countermoves, and Ultra Finishers in this iconic dark fantasy fighter.',
    gradientClass: 'cover-gradient-4',
    icon: 'fa-bolt',
    system: 'snes'
  },
  {
    id: 'mega_man_x',
    title: 'Mega Man X',
    publisher: 'Capcom',
    year: 1993,
    genre: 'Action-Platformer',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Mega%20Man%20X%20%28USA%29.zip',
    description: 'Jump, slide down walls, and gather armor modifications to defeat the rebellious Reploid Mavericks led by Sigma.',
    gradientClass: 'cover-gradient-1',
    icon: 'fa-biohazard',
    system: 'snes'
  },
  {
    id: 'final_fight',
    title: 'Final Fight',
    publisher: 'Capcom',
    year: 1990,
    genre: 'Beat \'Em Up',
    romUrl: 'https://archive.org/download/super-nintendo-snes-rom-collection-usa/Final%20Fight%20%28USA%29.zip',
    description: 'Clean up Metro City streets alongside Haggar and Cody to locate and save Haggar\'s daughter from the Mad Gear gang.',
    gradientClass: 'cover-gradient-2',
    icon: 'fa-hand-fist',
    system: 'snes'
  },
]